# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-26 06:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0009_auto_20170626_0600'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('f', 'facebook'), ('d', 'django')], default='d', max_length=1),
        ),
    ]
