# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-26 10:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0007_auto_20170620_0642'),
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_id', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('title', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.TextField()),
                ('thumbnail', models.ImageField(blank=True, upload_to='youtube')),
                ('created_date', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
