# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-26 11:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0008_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='post',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='post.Post'),
        ),
    ]
